// 기본 도시 시드 데이터(도시 테이블 비었을 때 1회 입력용) = routes.ts 분리(2026-07-15 §0 슬림화, 순수 이동)
// 아시아/미주 13개 + 이탈리아 4개 + 프랑스 30개 (part 1/2, 나머지는 default-cities-seed-2.ts)

export interface DefaultCitySeed {
  name: string;
  country: string;
  countryCode: string;
  latitude: number;
  longitude: number;
  timezone: string;
  primaryLanguage: string;
}

export const DEFAULT_CITIES_PART1: DefaultCitySeed[] = [
  // ===== 기존 아시아/미주 13개 =====
  {
    name: "서울",
    country: "대한민국",
    countryCode: "KR",
    latitude: 37.5665,
    longitude: 126.978,
    timezone: "Asia/Seoul",
    primaryLanguage: "ko",
  },
  {
    name: "도쿄",
    country: "일본",
    countryCode: "JP",
    latitude: 35.6762,
    longitude: 139.6503,
    timezone: "Asia/Tokyo",
    primaryLanguage: "ja",
  },
  {
    name: "오사카",
    country: "일본",
    countryCode: "JP",
    latitude: 34.6937,
    longitude: 135.5023,
    timezone: "Asia/Tokyo",
    primaryLanguage: "ja",
  },
  {
    name: "파리",
    country: "프랑스",
    countryCode: "FR",
    latitude: 48.8566,
    longitude: 2.3522,
    timezone: "Europe/Paris",
    primaryLanguage: "fr",
  },
  {
    name: "로마",
    country: "이탈리아",
    countryCode: "IT",
    latitude: 41.9028,
    longitude: 12.4964,
    timezone: "Europe/Rome",
    primaryLanguage: "it",
  },
  {
    name: "방콕",
    country: "태국",
    countryCode: "TH",
    latitude: 13.7563,
    longitude: 100.5018,
    timezone: "Asia/Bangkok",
    primaryLanguage: "th",
  },
  {
    name: "뉴욕",
    country: "미국",
    countryCode: "US",
    latitude: 40.7128,
    longitude: -74.006,
    timezone: "America/New_York",
    primaryLanguage: "en",
  },
  {
    name: "런던",
    country: "영국",
    countryCode: "GB",
    latitude: 51.5074,
    longitude: -0.1278,
    timezone: "Europe/London",
    primaryLanguage: "en",
  },
  {
    name: "바르셀로나",
    country: "스페인",
    countryCode: "ES",
    latitude: 41.3851,
    longitude: 2.1734,
    timezone: "Europe/Madrid",
    primaryLanguage: "es",
  },
  {
    name: "싱가포르",
    country: "싱가포르",
    countryCode: "SG",
    latitude: 1.3521,
    longitude: 103.8198,
    timezone: "Asia/Singapore",
    primaryLanguage: "en",
  },
  {
    name: "홍콩",
    country: "홍콩",
    countryCode: "HK",
    latitude: 22.3193,
    longitude: 114.1694,
    timezone: "Asia/Hong_Kong",
    primaryLanguage: "zh",
  },
  {
    name: "다낭",
    country: "베트남",
    countryCode: "VN",
    latitude: 16.0544,
    longitude: 108.2022,
    timezone: "Asia/Ho_Chi_Minh",
    primaryLanguage: "vi",
  },
  {
    name: "하노이",
    country: "베트남",
    countryCode: "VN",
    latitude: 21.0285,
    longitude: 105.8542,
    timezone: "Asia/Ho_Chi_Minh",
    primaryLanguage: "vi",
  },

  // ===== 유럽 30개 도시 (1차 목표) =====
  // 이탈리아
  {
    name: "밀라노",
    country: "이탈리아",
    countryCode: "IT",
    latitude: 45.4642,
    longitude: 9.19,
    timezone: "Europe/Rome",
    primaryLanguage: "it",
  },
  {
    name: "피렌체",
    country: "이탈리아",
    countryCode: "IT",
    latitude: 43.7696,
    longitude: 11.2558,
    timezone: "Europe/Rome",
    primaryLanguage: "it",
  },
  {
    name: "베니스",
    country: "이탈리아",
    countryCode: "IT",
    latitude: 45.4408,
    longitude: 12.3155,
    timezone: "Europe/Rome",
    primaryLanguage: "it",
  },
  {
    name: "나폴리",
    country: "이탈리아",
    countryCode: "IT",
    latitude: 40.8518,
    longitude: 14.2681,
    timezone: "Europe/Rome",
    primaryLanguage: "it",
  },
  // 프랑스 (30개 관광도시 - 1차 목표)
  {
    name: "니스",
    country: "프랑스",
    countryCode: "FR",
    latitude: 43.7102,
    longitude: 7.262,
    timezone: "Europe/Paris",
    primaryLanguage: "fr",
  },
  {
    name: "리옹",
    country: "프랑스",
    countryCode: "FR",
    latitude: 45.764,
    longitude: 4.8357,
    timezone: "Europe/Paris",
    primaryLanguage: "fr",
  },
  {
    name: "마르세유",
    country: "프랑스",
    countryCode: "FR",
    latitude: 43.2965,
    longitude: 5.3698,
    timezone: "Europe/Paris",
    primaryLanguage: "fr",
  },
  {
    name: "보르도",
    country: "프랑스",
    countryCode: "FR",
    latitude: 44.8378,
    longitude: -0.5792,
    timezone: "Europe/Paris",
    primaryLanguage: "fr",
  },
  {
    name: "스트라스부르",
    country: "프랑스",
    countryCode: "FR",
    latitude: 48.5734,
    longitude: 7.7521,
    timezone: "Europe/Paris",
    primaryLanguage: "fr",
  },
  {
    name: "툴루즈",
    country: "프랑스",
    countryCode: "FR",
    latitude: 43.6047,
    longitude: 1.4442,
    timezone: "Europe/Paris",
    primaryLanguage: "fr",
  },
  {
    name: "몽펠리에",
    country: "프랑스",
    countryCode: "FR",
    latitude: 43.6108,
    longitude: 3.8767,
    timezone: "Europe/Paris",
    primaryLanguage: "fr",
  },
  {
    name: "낭트",
    country: "프랑스",
    countryCode: "FR",
    latitude: 47.2184,
    longitude: -1.5536,
    timezone: "Europe/Paris",
    primaryLanguage: "fr",
  },
  {
    name: "칸",
    country: "프랑스",
    countryCode: "FR",
    latitude: 43.5528,
    longitude: 7.0174,
    timezone: "Europe/Paris",
    primaryLanguage: "fr",
  },
  {
    name: "아비뇽",
    country: "프랑스",
    countryCode: "FR",
    latitude: 43.9493,
    longitude: 4.8055,
    timezone: "Europe/Paris",
    primaryLanguage: "fr",
  },
  {
    name: "엑상프로방스",
    country: "프랑스",
    countryCode: "FR",
    latitude: 43.5297,
    longitude: 5.4474,
    timezone: "Europe/Paris",
    primaryLanguage: "fr",
  },
  {
    name: "콜마르",
    country: "프랑스",
    countryCode: "FR",
    latitude: 48.0794,
    longitude: 7.3558,
    timezone: "Europe/Paris",
    primaryLanguage: "fr",
  },
  {
    name: "앙시",
    country: "프랑스",
    countryCode: "FR",
    latitude: 45.8992,
    longitude: 6.1294,
    timezone: "Europe/Paris",
    primaryLanguage: "fr",
  },
  {
    name: "디종",
    country: "프랑스",
    countryCode: "FR",
    latitude: 47.322,
    longitude: 5.0415,
    timezone: "Europe/Paris",
    primaryLanguage: "fr",
  },
  {
    name: "루앙",
    country: "프랑스",
    countryCode: "FR",
    latitude: 49.4432,
    longitude: 1.0993,
    timezone: "Europe/Paris",
    primaryLanguage: "fr",
  },
  {
    name: "릴",
    country: "프랑스",
    countryCode: "FR",
    latitude: 50.6292,
    longitude: 3.0573,
    timezone: "Europe/Paris",
    primaryLanguage: "fr",
  },
  {
    name: "렌",
    country: "프랑스",
    countryCode: "FR",
    latitude: 48.1173,
    longitude: -1.6778,
    timezone: "Europe/Paris",
    primaryLanguage: "fr",
  },
  {
    name: "카르카손",
    country: "프랑스",
    countryCode: "FR",
    latitude: 43.213,
    longitude: 2.3491,
    timezone: "Europe/Paris",
    primaryLanguage: "fr",
  },
  {
    name: "비아리츠",
    country: "프랑스",
    countryCode: "FR",
    latitude: 43.4832,
    longitude: -1.5586,
    timezone: "Europe/Paris",
    primaryLanguage: "fr",
  },
  {
    name: "생말로",
    country: "프랑스",
    countryCode: "FR",
    latitude: 48.6493,
    longitude: -2.0007,
    timezone: "Europe/Paris",
    primaryLanguage: "fr",
  },
  {
    name: "샤모니",
    country: "프랑스",
    countryCode: "FR",
    latitude: 45.9237,
    longitude: 6.8694,
    timezone: "Europe/Paris",
    primaryLanguage: "fr",
  },
  {
    name: "아를",
    country: "프랑스",
    countryCode: "FR",
    latitude: 43.6767,
    longitude: 4.6278,
    timezone: "Europe/Paris",
    primaryLanguage: "fr",
  },
  {
    name: "생트로페",
    country: "프랑스",
    countryCode: "FR",
    latitude: 43.2727,
    longitude: 6.6406,
    timezone: "Europe/Paris",
    primaryLanguage: "fr",
  },
  {
    name: "베르사유",
    country: "프랑스",
    countryCode: "FR",
    latitude: 48.8014,
    longitude: 2.1301,
    timezone: "Europe/Paris",
    primaryLanguage: "fr",
  },
  {
    name: "그르노블",
    country: "프랑스",
    countryCode: "FR",
    latitude: 45.1885,
    longitude: 5.7245,
    timezone: "Europe/Paris",
    primaryLanguage: "fr",
  },
  {
    name: "랭스",
    country: "프랑스",
    countryCode: "FR",
    latitude: 49.2583,
    longitude: 4.0317,
    timezone: "Europe/Paris",
    primaryLanguage: "fr",
  },
  {
    name: "안티브",
    country: "프랑스",
    countryCode: "FR",
    latitude: 43.5808,
    longitude: 7.1239,
    timezone: "Europe/Paris",
    primaryLanguage: "fr",
  },
  {
    name: "망통",
    country: "프랑스",
    countryCode: "FR",
    latitude: 43.7764,
    longitude: 7.5048,
    timezone: "Europe/Paris",
    primaryLanguage: "fr",
  },
  {
    name: "투르",
    country: "프랑스",
    countryCode: "FR",
    latitude: 47.3941,
    longitude: 0.6848,
    timezone: "Europe/Paris",
    primaryLanguage: "fr",
  },
];
