// ⚠️ 수정금지(승인필요) 2026-08-28 사장님 승인 = place_seed_raw PID 중복그룹의 "흡수 후보 컬럼" 목록 1벌(§16 SSOT).
export const FILL_COLS = [
  "name_ko",
  "name_en",
  "name_local",
  "image_url",
  "image_attribution",
  "price_eur",
  "editorial_summary",
  "summary_ko",
  "address",
  "latitude",
  "longitude",
  "google_review_count",
  "google_rating",
  "google_maps_uri",
  "google_primary_type",
  "opening_hours",
  "vibe_keywords",
  "phase_tags",
  "category_tags",
  "names_i18n",
  "photo_urls",
  "distance_km_from_center",
  "day_zone",
] as const;
