import { StyleSheet } from "react-native";
import { Spacing, BorderRadius, Brand, Fonts } from "@/constants/theme";

export const styles = StyleSheet.create({
  container: { flex: 1 },
  scroll: { flex: 1 },
  flex1: { flex: 1 },
  attachCard: {
    padding: Spacing.md,
    borderRadius: BorderRadius.md,
    marginBottom: Spacing.md,
    gap: Spacing.xs,
  },
  cardTitle: { fontSize: 16, fontFamily: Fonts.bold, marginBottom: 2 },
  cardSub: { fontSize: 13, fontFamily: Fonts.medium },
  cardBio: { fontSize: 12, fontFamily: Fonts.medium, marginTop: 4 },
  sectionTitle: {
    fontSize: 16,
    fontFamily: Fonts.bold,
    marginBottom: Spacing.sm,
  },
  attachTitle: { fontSize: 18, fontFamily: Fonts.bold },
  aiLine: {
    flexDirection: "row",
    alignItems: "center",
    gap: Spacing.sm,
    padding: Spacing.sm,
    borderRadius: BorderRadius.sm,
    marginTop: 4,
  },
  dot: { width: 8, height: 8, borderRadius: 4, backgroundColor: "#7A5AF8" },
  aiText: { flex: 1, fontSize: 12, fontFamily: Fonts.medium }, // color = 인라인(다크모드 대응)
  input: {
    padding: Spacing.md,
    borderRadius: BorderRadius.md,
    fontSize: 15,
    fontFamily: Fonts.medium,
    minHeight: 100,
    textAlignVertical: "top",
    marginBottom: Spacing.md,
  },
  submitBtn: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: Spacing.sm,
    height: Spacing.buttonHeight,
    borderRadius: BorderRadius.md,
  },
  submitText: { color: "#FFF", fontSize: 16, fontFamily: Fonts.bold },
  creditNote: {
    fontSize: 12,
    fontFamily: Fonts.medium,
    textAlign: "center",
    marginTop: Spacing.sm,
  },
  divider: {
    borderTopWidth: StyleSheet.hairlineWidth,
    marginVertical: Spacing.xl,
  },
  emptyText: {
    fontSize: 14,
    fontFamily: Fonts.medium,
    textAlign: "center",
    paddingVertical: Spacing.lg,
  },
  inquiryCard: {
    flexDirection: "row",
    alignItems: "center",
    gap: Spacing.sm,
    padding: Spacing.md,
    borderRadius: BorderRadius.md,
    marginBottom: Spacing.sm,
  },
  unreadDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: Brand.primary,
  },
  inquiryTitle: { fontSize: 14, fontFamily: Fonts.semiBold },
  inquiryPreview: { fontSize: 12, fontFamily: Fonts.medium, marginTop: 2 },
  badge: {
    paddingHorizontal: Spacing.sm,
    paddingVertical: 4,
    borderRadius: BorderRadius.full,
  },
  badgeText: { fontSize: 11, fontFamily: Fonts.bold },
  chips: { gap: Spacing.sm, paddingBottom: Spacing.md },
  chip: {
    paddingHorizontal: Spacing.md,
    paddingVertical: Spacing.sm,
    borderRadius: BorderRadius.full,
    borderWidth: 1,
  },
  chipText: { fontSize: 13, fontFamily: Fonts.semiBold },
  empty: {
    fontSize: 14,
    fontFamily: Fonts.medium,
    textAlign: "center",
    paddingVertical: Spacing.xl,
  },
  detailHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: Spacing.sm,
    paddingHorizontal: Spacing.md,
    paddingTop: Spacing.sm,
    paddingBottom: Spacing.md,
    borderBottomWidth: StyleSheet.hairlineWidth,
  },
  backBtn: {
    width: 32,
    height: 32,
    justifyContent: "center",
    alignItems: "center",
  },
  detailTitle: { flex: 1, fontSize: 18, fontFamily: Fonts.bold },
  badgePlaceholder: { width: 44 },
  center: { flex: 1, justifyContent: "center", alignItems: "center" },
  attach: {
    flexDirection: "row",
    alignItems: "center",
    gap: Spacing.xs,
    padding: Spacing.sm,
    borderRadius: BorderRadius.sm,
    marginBottom: Spacing.lg,
  },
  attachText: { flex: 1, fontSize: 12, fontFamily: Fonts.medium },
  attachFull: {
    flexDirection: "row",
    alignItems: "center",
    padding: Spacing.md,
    borderRadius: BorderRadius.md,
    borderWidth: StyleSheet.hairlineWidth,
    marginBottom: Spacing.lg,
  },
  attachHead: { fontSize: 14, fontFamily: Fonts.bold },
  attachMeta: { fontSize: 12, fontFamily: Fonts.medium, marginTop: 2 },
  attachOpen: {
    fontSize: 12,
    fontFamily: Fonts.semiBold,
    marginTop: Spacing.sm,
  },
  from: { fontSize: 11, fontFamily: Fonts.medium, marginBottom: 4 },
  bubble: {
    maxWidth: "88%",
    padding: Spacing.md,
    borderRadius: BorderRadius.md,
    marginBottom: Spacing.lg,
  },
  bubbleMe: { alignSelf: "flex-end", borderBottomRightRadius: 4 },
  bubbleMeText: {
    color: "#FFF",
    fontSize: 14,
    fontFamily: Fonts.medium,
    lineHeight: 21,
  },
  bubbleThem: { alignSelf: "flex-start", borderBottomLeftRadius: 4 },
  bubbleThemText: { fontSize: 14, fontFamily: Fonts.medium, lineHeight: 21 },
  waiting: {
    flexDirection: "row",
    alignItems: "center",
    gap: Spacing.sm,
    alignSelf: "flex-start",
    padding: Spacing.md,
    borderRadius: BorderRadius.md,
  },
  waitingText: { fontSize: 13, fontFamily: Fonts.semiBold },
  replyBox: {
    borderTopWidth: StyleSheet.hairlineWidth,
    paddingTop: Spacing.lg,
    marginTop: Spacing.sm,
  },
  replyLabel: {
    fontSize: 14,
    fontFamily: Fonts.bold,
    marginBottom: Spacing.sm,
  },
  doneRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: Spacing.sm,
    padding: Spacing.md,
    borderRadius: BorderRadius.md,
    marginBottom: Spacing.md,
  },
  doneText: { fontSize: 14, fontFamily: Fonts.bold },
  editBtn: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
    height: Spacing.buttonHeight,
    borderRadius: BorderRadius.md,
    borderWidth: StyleSheet.hairlineWidth,
  },
  editText: { fontSize: 14, fontFamily: Fonts.semiBold },
  replyInput: {
    padding: Spacing.md,
    borderRadius: BorderRadius.md,
    fontSize: 15,
    fontFamily: Fonts.medium,
    minHeight: 90,
    textAlignVertical: "top",
    marginBottom: Spacing.md,
  },
  replyActions: { flexDirection: "row", gap: Spacing.sm },
  actBtn: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 4,
    height: Spacing.buttonHeight,
    borderRadius: BorderRadius.md,
    paddingHorizontal: Spacing.md,
  },
  actPrimary: { flex: 1 },
  actText: { fontSize: 13, fontFamily: Fonts.bold },
  pfHeader: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: Spacing.md,
    paddingTop: Spacing.sm,
    paddingBottom: Spacing.md,
    borderBottomWidth: StyleSheet.hairlineWidth,
  },
  pfBack: {
    width: 40,
    height: 40,
    justifyContent: "center",
    alignItems: "center",
  },
  pfTitle: {
    flex: 1,
    fontSize: 20,
    fontFamily: Fonts.bold,
    letterSpacing: -0.5,
    textAlign: "center",
  },
  pfLabel: {
    fontSize: 14,
    fontFamily: Fonts.semiBold,
    marginBottom: Spacing.xs,
    marginTop: Spacing.md,
  },
  pfInput: {
    padding: Spacing.md,
    borderRadius: BorderRadius.md,
    fontSize: 15,
    fontFamily: Fonts.medium,
  },
  pfInputMultiline: { minHeight: 100, textAlignVertical: "top" },
  saveBtn: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: Spacing.sm,
    height: Spacing.buttonHeight,
    borderRadius: BorderRadius.md,
    marginTop: Spacing.xl,
  },
  saveText: { color: "#FFF", fontSize: 16, fontFamily: Fonts.bold },
});
