import { StyleSheet, Dimensions } from "react-native";
import {
  Spacing,
  BorderRadius,
  Typography,
  Shadows,
  Fonts,
  Brand,
} from "@/constants/theme";

const { width: SCREEN_WIDTH } = Dimensions.get("window");

// 📱 아이폰 12 (390pt) 화면을 가득 채우는 풍성한 가로 스크롤 카드 폭 계산 (250pt)
export const getResponsiveFullTripCardWidth = () => {
  return Math.min(270, Math.max(220, Math.floor(SCREEN_WIDTH * 0.65)));
};

export const getResponsiveFullVideoCardWidth = () => {
  return Math.min(135, Math.max(115, Math.floor(SCREEN_WIDTH * 0.32)));
};

export const styles = StyleSheet.create({
  // 👤 3D 입체 프로필 헤더 카드 (슬림 초슬림 컴팩트 1섹션)
  profileCard: {
    alignItems: "center",
    marginBottom: 10,
    paddingHorizontal: 14,
    paddingVertical: 10,
    width: "100%",
    borderRadius: 22,
    backgroundColor: "#FFFFFF",
    ...Shadows.card,
    borderWidth: 1,
    borderColor: "rgba(226, 232, 240, 0.8)",
  },
  profileTopRow: {
    width: "100%",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 8,
  },
  profileUserInfoLeft: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    flexShrink: 1,
  },
  avatarGradientCompact: {
    width: 44,
    height: 44,
    borderRadius: 22,
    justifyContent: "center",
    alignItems: "center",
    borderWidth: 2,
    borderColor: "#FFFFFF",
    ...Shadows.card,
  },
  userTextContainer: {
    justifyContent: "center",
    flexShrink: 1,
  },
  userNameCompact: {
    fontSize: 16,
    fontFamily: Fonts.bold,
    color: "#0F172A",
    lineHeight: 20,
  },
  userEmailCompact: {
    fontSize: 11.5,
    fontFamily: Fonts.medium,
    color: "#64748B",
    marginTop: 1,
  },
  // 💳 초슬림 3D 1줄 크레딧 카드 (높이 34px)
  creditCardCompact: {
    width: "100%",
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 14,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    backgroundColor: "#F8FAFC",
    borderWidth: 1,
    borderColor: "#E2E8F0",
  },
  creditLeftCompact: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    flexShrink: 1,
  },
  creditIconCircleCompact: {
    width: 26,
    height: 26,
    borderRadius: 13,
    backgroundColor: "rgba(66, 133, 244, 0.12)",
    justifyContent: "center",
    alignItems: "center",
  },
  creditLabelCompact: {
    fontSize: 11.5,
    fontFamily: Fonts.medium,
    color: "#64748B",
  },
  creditValueCompact: {
    fontSize: 14,
    fontFamily: Fonts.bold,
    color: "#0F172A",
  },
  creditRechargeBtnCompact: {
    backgroundColor: Brand.primary,
    paddingHorizontal: 12,
    paddingVertical: 5,
    borderRadius: BorderRadius.full,
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
  },
  creditRechargeTextCompact: {
    color: "#FFFFFF",
    fontSize: 11.5,
    fontFamily: Fonts.bold,
  },
  loginButton: {
    marginTop: Spacing.md,
    paddingHorizontal: Spacing.xl,
    paddingVertical: Spacing.md,
    borderRadius: BorderRadius.full,
  },
  loginButtonText: {
    color: "#FFFFFF",
    fontSize: 14,
    fontFamily: Fonts.bold,
  },
  // 🏷️ 섹션 영역 (아이폰 12 가득 채움)
  section: {
    marginBottom: 24,
    width: "100%",
  },
  sectionTitleHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    marginBottom: 12,
  },
  sectionIconBox: {
    width: 32,
    height: 32,
    borderRadius: 12,
    justifyContent: "center",
    alignItems: "center",
  },
  sectionTitle: {
    ...Typography.h3,
    fontFamily: Fonts.bold,
    fontSize: 18,
    color: "#0F172A",
  },
  sectionBadge: {
    fontSize: 11,
    fontFamily: Fonts.bold,
    color: Brand.primary,
    backgroundColor: "rgba(66, 133, 244, 0.12)",
    paddingHorizontal: 9,
    paddingVertical: 3,
    borderRadius: BorderRadius.full,
  },
  // 🗂️ 나의 여정 풍성한 3D 입체 카드 (아이폰 12 가득 채움)
  loadingContainer: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    padding: Spacing.lg,
    gap: Spacing.sm,
  },
  loadingText: {
    fontSize: 13,
  },
  emptyTrips: {
    alignItems: "center",
    padding: Spacing.xl,
    borderRadius: 22,
    borderWidth: 1,
    width: "100%",
  },
  emptyTripsText: {
    fontSize: 15,
    fontFamily: Fonts.bold,
    marginTop: Spacing.sm,
  },
  emptyTripsHint: {
    fontSize: 12,
    marginTop: Spacing.xs,
  },
  tripsScroll: {
    marginHorizontal: -16,
    paddingHorizontal: 16,
  },
  tripCardRich: {
    padding: 14,
    position: "relative",
    borderRadius: 24,
    marginRight: 12,
    backgroundColor: "#FFFFFF",
    ...Shadows.elevated,
    borderWidth: 1.5,
    borderColor: "#E2E8F0",
  },
  cardDeleteBtnRich: {
    position: "absolute",
    top: 10,
    right: 10,
    width: 24,
    height: 24,
    borderRadius: 12,
    backgroundColor: "rgba(100, 116, 139, 0.15)",
    justifyContent: "center",
    alignItems: "center",
    zIndex: 10,
  },
  cardHeaderRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 4,
    paddingRight: 24,
  },
  cardCityRich: {
    fontSize: 17,
    fontFamily: Fonts.bold,
    color: "#0F172A",
  },
  cardMetaRich: {
    fontSize: 11,
    fontFamily: Fonts.medium,
    color: "#64748B",
    marginBottom: 6,
  },
  cardBudgetPill: {
    alignSelf: "flex-start",
    backgroundColor: "rgba(66, 133, 244, 0.12)",
    paddingHorizontal: 9,
    paddingVertical: 3,
    borderRadius: 8,
    fontSize: 12,
    fontFamily: Fonts.bold,
    color: Brand.primary,
    marginBottom: 8,
  },
  cardSummaryRich: {
    fontSize: 12,
    fontFamily: Fonts.medium,
    color: "#475569",
    lineHeight: 17,
  },
  // 🎬 나의 숏폼 영상 입체 3D 카드
  videoCardRich: {
    aspectRatio: 9 / 16,
    borderRadius: 20,
    marginRight: 10,
    overflow: "hidden",
    position: "relative",
    ...Shadows.elevated,
    borderWidth: 1.5,
    borderColor: "rgba(255, 255, 255, 0.4)",
  },
  videoThumbnail: {
    width: "100%",
    height: "100%",
    position: "relative",
  },
  videoThumbnailGradient: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
  },
  videoPlayOverlayRich: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: "rgba(0, 0, 0, 0.4)",
    justifyContent: "center",
    alignItems: "center",
    borderWidth: 1.5,
    borderColor: "rgba(255, 255, 255, 0.8)",
    boxShadow: "0 4px 12px rgba(0,0,0,0.3)",
  },
  videoInfoOverlay: {
    position: "absolute",
    bottom: 0,
    left: 0,
    right: 0,
    padding: 8,
    backgroundColor: "rgba(15, 23, 42, 0.75)",
  },
  videoCardTitle: {
    fontSize: 11,
    fontFamily: Fonts.bold,
    color: "#FFFFFF",
  },
  videoCardDate: {
    fontSize: 9,
    fontFamily: Fonts.medium,
    color: "rgba(255, 255, 255, 0.8)",
  },
  // 🔧 설정 아코디언 카드 (아이폰 12 가득 채움)
  accordionCard: {
    width: "100%",
    borderRadius: 26,
    backgroundColor: "#FFFFFF",
    overflow: "hidden",
    ...Shadows.elevated,
    borderWidth: 1.5,
    borderColor: "#E2E8F0",
  },
  accordionItemHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 18,
    paddingVertical: 16,
  },
  accordionItemLeft: {
    flexDirection: "row",
    alignItems: "center",
    gap: 14,
  },
  menuIconCircle: {
    width: 36,
    height: 36,
    borderRadius: 12,
    justifyContent: "center",
    alignItems: "center",
  },
  accordionItemLabel: {
    ...Typography.body,
    fontSize: 16,
    fontFamily: Fonts.bold,
    color: "#0F172A",
  },
  accordionBody: {
    paddingHorizontal: 18,
    paddingVertical: 14,
    backgroundColor: "#F8FAFC",
    borderTopWidth: 1,
    borderTopColor: "#E2E8F0",
  },
  accordionText: {
    fontSize: 13,
    fontFamily: Fonts.regular,
    color: "#475569",
    lineHeight: 19,
    marginBottom: 6,
  },
  chipContainer: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
    marginTop: 8,
  },
  chipBtn: {
    paddingHorizontal: 13,
    paddingVertical: 7,
    borderRadius: 18,
    borderWidth: 1.5,
    backgroundColor: "#FFFFFF",
  },
  chipBtnText: {
    fontSize: 12,
    fontFamily: Fonts.bold,
  },
  // 🚪 독립 분리형 개별 로그아웃 카드 (가득 채움)
  logoutSeparateCard: {
    width: "100%",
    marginTop: 16,
    marginBottom: 28,
    paddingVertical: 16,
    paddingHorizontal: 20,
    borderRadius: 22,
    backgroundColor: "rgba(239, 68, 68, 0.08)",
    borderWidth: 1.5,
    borderColor: "rgba(239, 68, 68, 0.25)",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 10,
    ...Shadows.card,
  },
  logoutSeparateText: {
    fontSize: 16,
    fontFamily: Fonts.bold,
    color: "#EF4444",
  },
});
